# Generated by Django 3.1.6 on 2021-03-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acrotrainer', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAdress',
            new_name='ShippingAddress',
        ),
    ]
