# Generated by Django 3.1.6 on 2021-03-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrotrainer', '0003_auto_20210307_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
